# Generated by Django 6.0.3 on 2026-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi bi-mortarboard-fill', max_length=60, verbose_name='Bootstrap Icon')),
                ('title_ru', models.CharField(max_length=120, verbose_name='Заголовок (рус)')),
                ('title_kg', models.CharField(max_length=120, verbose_name='Заголовок (кырг)')),
                ('text_ru', models.TextField(verbose_name='Текст (рус)')),
                ('text_kg', models.TextField(verbose_name='Текст (кырг)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': '✅ Преимущество школы',
                'verbose_name_plural': '✅ Преимущества школы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='Школа с богатой историей', max_length=200, verbose_name='Заголовок (рус)')),
                ('title_kg', models.CharField(default='Бай тарыхы бар мектеп', max_length=200, verbose_name='Заголовок (кырг)')),
                ('text_ru', models.TextField(verbose_name='Текст (рус)')),
                ('text_kg', models.TextField(verbose_name='Текст (кырг)')),
                ('photo', models.ImageField(blank=True, help_text='800×600px', null=True, upload_to='about/', verbose_name='Фото здания')),
                ('accreditation_badge_ru', models.CharField(default='Аккредитована', max_length=60, verbose_name='Бейдж аккредитации (рус)')),
                ('accreditation_badge_kg', models.CharField(default='Аккредитацияланган', max_length=60, verbose_name='Бейдж аккредитации (кырг)')),
                ('accreditation_org_ru', models.CharField(default='МОиН КР', max_length=60, verbose_name='Орган аккредитации (рус)')),
                ('accreditation_org_kg', models.CharField(default='КР БИМ', max_length=60, verbose_name='Орган аккредитации (кырг)')),
            ],
            options={
                'verbose_name': 'ℹ️ О школе (текст и фото)',
                'verbose_name_plural': 'ℹ️ О школе (текст и фото)',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi bi-trophy-fill', max_length=60, verbose_name='Bootstrap Icon')),
                ('color', models.CharField(choices=[('gold', '🥇 Золотой'), ('blue', '🔵 Синий'), ('green', '🟢 Зелёный'), ('red', '🔴 Красный')], default='gold', max_length=10, verbose_name='Цвет иконки')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (рус)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (кырг)')),
                ('text_ru', models.TextField(verbose_name='Текст (рус)')),
                ('text_kg', models.TextField(verbose_name='Текст (кырг)')),
                ('year', models.CharField(help_text='2024 или 2023–2024', max_length=20, verbose_name='Год')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': '🏆 Достижение',
                'verbose_name_plural': '🏆 Достижения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('grade', models.CharField(blank=True, max_length=30, verbose_name='Класс / Возраст')),
                ('language', models.CharField(blank=True, choices=[('ru', 'Русский'), ('kg', 'Кыргызский')], max_length=5, verbose_name='Язык обучения')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', '🆕 Новая'), ('contacted', '📞 Связались'), ('enrolled', '✅ Записан'), ('declined', '❌ Отказ')], default='new', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки (внутренние)')),
            ],
            options={
                'verbose_name': '📩 Заявка на запись',
                'verbose_name_plural': '📩 Заявки на запись',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ru', models.CharField(default='г. Бишкек, ул. Примерная, 1', max_length=200, verbose_name='Адрес (рус)')),
                ('address_kg', models.CharField(default='Бишкек ш., Үлгүлүү к., 1', max_length=200, verbose_name='Адрес (кырг)')),
                ('phone', models.CharField(default='+996 312 00-00-00', max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours_ru', models.CharField(default='Пн–Сб, 8:00 – 18:00', max_length=80, verbose_name='Режим работы (рус)')),
                ('working_hours_kg', models.CharField(default='Дш–Иш, 8:00 – 18:00', max_length=80, verbose_name='Режим работы (кырг)')),
                ('map_embed_url', models.URLField(blank=True, help_text='Ссылка из «Встроить карту» в Google Maps', verbose_name='Ссылка Google Maps (embed)')),
                ('telegram_url', models.URLField(blank=True, help_text='https://t.me/...', verbose_name='Telegram')),
                ('whatsapp_number', models.CharField(blank=True, help_text='996312000000 без + и пробелов', max_length=20, verbose_name='WhatsApp номер')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': '📞 Контакты',
                'verbose_name_plural': '📞 Контакты',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='1200×500px', upload_to='gallery/', verbose_name='Фото')),
                ('caption_ru', models.CharField(blank=True, max_length=120, verbose_name='Подпись (рус)')),
                ('caption_kg', models.CharField(blank=True, max_length=120, verbose_name='Подпись (кырг)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок в карусели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': '🖼️ Фото галереи',
                'verbose_name_plural': '🖼️ Галерея',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_ru', models.CharField(default='Приём на 2025/2026 год открыт', max_length=120, verbose_name='Бейдж (рус)')),
                ('badge_kg', models.CharField(default='2025/2026-окуу жылына кабыл алуу ачык', max_length=120, verbose_name='Бейдж (кырг)')),
                ('title_ru', models.CharField(default='Качественное образование', max_length=120, verbose_name='Заголовок строка 1 (рус)')),
                ('title_kg', models.CharField(default='Сапаттуу билим', max_length=120, verbose_name='Заголовок строка 1 (кырг)')),
                ('title_accent_ru', models.CharField(default='для каждого ребёнка', max_length=120, verbose_name='Заголовок строка 2 (рус)')),
                ('title_accent_kg', models.CharField(default='ар бир бала үчүн', max_length=120, verbose_name='Заголовок строка 2 (кырг)')),
                ('description_ru', models.TextField(default='Школа №1 — современное учебное заведение.', verbose_name='Описание (рус)')),
                ('description_kg', models.TextField(default='№1 мектеп — заманбап билим берүү мекемеси.', verbose_name='Описание (кырг)')),
                ('btn_apply_ru', models.CharField(default='Оставить заявку', max_length=60, verbose_name="Кнопка 'Записаться' (рус)")),
                ('btn_apply_kg', models.CharField(default='Билдирме калтыруу', max_length=60, verbose_name="Кнопка 'Записаться' (кырг)")),
            ],
            options={
                'verbose_name': '🌟 Hero-секция (главный экран)',
                'verbose_name_plural': '🌟 Hero-секция (главный экран)',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi bi-book-fill', max_length=60, verbose_name='Bootstrap Icon')),
                ('category', models.CharField(choices=[('basic', 'Основные'), ('extra', 'Внеурочные'), ('optional', 'Факультативы')], default='basic', max_length=20, verbose_name='Категория')),
                ('tag_ru', models.CharField(help_text='1–4 классы', max_length=40, verbose_name='Тег / классы (рус)')),
                ('tag_kg', models.CharField(max_length=40, verbose_name='Тег / классы (кырг)')),
                ('name_ru', models.CharField(max_length=120, verbose_name='Название (рус)')),
                ('name_kg', models.CharField(max_length=120, verbose_name='Название (кырг)')),
                ('description_ru', models.TextField(verbose_name='Описание (рус)')),
                ('description_kg', models.TextField(verbose_name='Описание (кырг)')),
                ('duration_ru', models.CharField(help_text='4 года', max_length=30, verbose_name='Длительность (рус)')),
                ('duration_kg', models.CharField(max_length=30, verbose_name='Длительность (кырг)')),
                ('class_size_ru', models.CharField(help_text='25 чел/класс', max_length=30, verbose_name='Кол-во в классе (рус)')),
                ('class_size_kg', models.CharField(max_length=30, verbose_name='Кол-во в классе (кырг)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': '📚 Программа',
                'verbose_name_plural': '📚 Программы обучения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(default='Школа №1', max_length=120, verbose_name='Название школы (рус)')),
                ('name_kg', models.CharField(default='№1 Мектеп', max_length=120, verbose_name='Название школы (кырг)')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер школы')),
                ('city_ru', models.CharField(default='г. Бишкек', max_length=80, verbose_name='Город (рус)')),
                ('city_kg', models.CharField(default='Бишкек ш.', max_length=80, verbose_name='Город (кырг)')),
                ('logo', models.ImageField(blank=True, help_text='PNG, ~200×200px', null=True, upload_to='logo/', verbose_name='Логотип')),
                ('primary_color', models.CharField(default='#0EA5E9', max_length=20, verbose_name='Основной цвет (hex)')),
                ('accent_color', models.CharField(default='#F59E0B', max_length=20, verbose_name='Акцентный цвет (hex)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=160, verbose_name='SEO заголовок (рус)')),
                ('seo_description_ru', models.TextField(blank=True, verbose_name='SEO описание (рус)')),
                ('seo_title_kg', models.CharField(blank=True, max_length=160, verbose_name='SEO заголовок (кырг)')),
                ('seo_description_kg', models.TextField(blank=True, verbose_name='SEO описание (кырг)')),
            ],
            options={
                'verbose_name': '⚙️ Настройки школы',
                'verbose_name_plural': '⚙️ Настройки школы',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Число')),
                ('suffix', models.CharField(blank=True, default='+', max_length=10, verbose_name='Суффикс (+ или %)')),
                ('label_ru', models.CharField(max_length=80, verbose_name='Подпись (рус)')),
                ('label_kg', models.CharField(max_length=80, verbose_name='Подпись (кырг)')),
                ('icon', models.CharField(default='bi bi-people', help_text='bi bi-people / bi bi-mortarboard / bi bi-clock-history', max_length=60, verbose_name='Bootstrap Icon')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': '📊 Статистика',
                'verbose_name_plural': '📊 Статистика',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Квадрат, ~400×400px', null=True, upload_to='teachers/', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('subject_ru', models.CharField(max_length=100, verbose_name='Предмет (рус)')),
                ('subject_kg', models.CharField(max_length=100, verbose_name='Предмет (кырг)')),
                ('category', models.CharField(choices=[('highest', 'Высшая категория'), ('first', 'Первая категория'), ('second', 'Вторая категория')], default='first', max_length=20, verbose_name='Квалификация')),
                ('experience_years', models.PositiveSmallIntegerField(default=5, verbose_name='Опыт (лет)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': '👨\u200d🏫 Педагог',
                'verbose_name_plural': '👨\u200d🏫 Педагоги',
                'ordering': ['order'],
            },
        ),
    ]
