# Generated by Django 6.0.3 on 2026-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order'], 'verbose_name': '📚 Программа обучения', 'verbose_name_plural': '📚 Программы обучения'},
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='primary_color',
        ),
        migrations.AlterField(
            model_name='aboutfeature',
            name='icon',
            field=models.CharField(default='bi bi-mortarboard-fill', help_text='bi bi-mortarboard-fill / bi bi-laptop / bi bi-translate / bi bi-shield-check', max_length=60, verbose_name='Иконка Bootstrap Icons'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='photo',
            field=models.ImageField(blank=True, help_text='Рекомендуется 800×600px', null=True, upload_to='about/', verbose_name='Фото школы'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='text_kg',
            field=models.TextField(verbose_name='Основной текст (кырг)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='text_ru',
            field=models.TextField(help_text='Например: Основана в 1993 году...', verbose_name='Основной текст (рус)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_kg',
            field=models.CharField(default='Бай тарыхы жана заманбап мамилеси бар мектеп', max_length=200, verbose_name='Заголовок (кырг)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(default='Школа с богатой историей и современным подходом', max_length=200, verbose_name='Заголовок (рус)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='bi bi-trophy-fill', max_length=60, verbose_name='Иконка Bootstrap Icons'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='text_kg',
            field=models.TextField(verbose_name='Описание (кырг)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='text_ru',
            field=models.TextField(verbose_name='Описание (рус)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='year',
            field=models.CharField(help_text='Например: 2024 или 2023–2024', max_length=20, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заявки'),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='grade',
            field=models.CharField(blank=True, max_length=30, verbose_name='Класс / Возраст ребёнка'),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Видны только в панели — родители не видят', verbose_name='Заметки администратора'),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Новая'), ('contacted', '📞 Связались'), ('enrolled', '✅ Записан'), ('declined', '❌ Отказ')], default='new', max_length=15, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='https://instagram.com/school_name', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Откройте Google Maps → ваш адрес → Поделиться → Встроить карту → скопируйте только URL из src="..."', max_length=1000, verbose_name='Google Maps embed URL'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='https://t.me/school_name', verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='996312000000 — только цифры, без + и пробелов', max_length=20, verbose_name='WhatsApp номер'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Рекомендуется 1200×500px (широкоформатное)', upload_to='gallery/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Позиция в карусели'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_accent_kg',
            field=models.CharField(default='ар бир бала үчүн', max_length=120, verbose_name='Заголовок строка 2 акцент (кырг)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_accent_ru',
            field=models.CharField(default='для каждого ребёнка', max_length=120, verbose_name='Заголовок строка 2 акцент (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('basic', 'Основные'), ('extra', 'Внеурочные'), ('optional', 'Факультативы')], default='basic', max_length=20, verbose_name='Категория программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='class_size_kg',
            field=models.CharField(max_length=30, verbose_name='Кол-во учеников (кырг)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='class_size_ru',
            field=models.CharField(help_text='Например: 25 чел/класс', max_length=30, verbose_name='Кол-во учеников (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_ru',
            field=models.CharField(help_text='Например: 4 года', max_length=30, verbose_name='Длительность (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.CharField(default='bi bi-book-fill', max_length=60, verbose_name='Иконка Bootstrap Icons'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_kg',
            field=models.CharField(max_length=120, verbose_name='Название программы (кырг)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_ru',
            field=models.CharField(max_length=120, verbose_name='Название программы (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tag_kg',
            field=models.CharField(help_text='Например: 1–4-класстар', max_length=40, verbose_name='Тег / классы (кырг)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tag_ru',
            field=models.CharField(help_text='Например: 1–4 классы', max_length=40, verbose_name='Тег / классы (рус)'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG с прозрачным фоном, ~200×200px', null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='number',
            field=models.CharField(blank=True, help_text='Например: №1', max_length=20, verbose_name='Номер школы'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(default='bi bi-people', help_text='bi bi-people / bi bi-mortarboard / bi bi-clock-history / bi bi-person-workspace', max_length=60, verbose_name='Иконка Bootstrap Icons'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='number',
            field=models.PositiveIntegerField(help_text='Например: 850', verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='suffix',
            field=models.CharField(blank=True, default='+', help_text='+ или %', max_length=10, verbose_name='Суффикс'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('highest', 'Высшая категория'), ('first', 'Первая категория'), ('second', 'Вторая категория')], default='first', max_length=20, verbose_name='Квалификационная категория'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Стаж (лет)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, help_text='Квадратное фото, ~400×400px', null=True, upload_to='teachers/', verbose_name='Фото педагога'),
        ),
    ]
