# Generated by Django 6.0.3 on 2026-04-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0002_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutfeature',
            options={'ordering': ['order'], 'verbose_name': 'Преимущество школы', 'verbose_name_plural': 'Преимущества школы'},
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'О школе (текст и фото)', 'verbose_name_plural': 'О школе (текст и фото)'},
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['order'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='applicationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на запись', 'verbose_name_plural': 'Заявки на запись'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Фото галереи', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero-секция (главный экран)', 'verbose_name_plural': 'Hero-секция (главный экран)'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order'], 'verbose_name': 'Программа обучения', 'verbose_name_plural': 'Программы обучения'},
        ),
        migrations.AlterModelOptions(
            name='schoolsettings',
            options={'verbose_name': 'Настройки школы', 'verbose_name_plural': 'Настройки школы'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order'], 'verbose_name': 'Педагог', 'verbose_name_plural': 'Педагоги'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='color',
            field=models.CharField(choices=[('gold', 'Золотой'), ('blue', 'Синий'), ('green', 'Зелёный'), ('red', 'Красный')], default='gold', max_length=10, verbose_name='Цвет иконки'),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='grade',
            field=models.CharField(blank=True, max_length=30, verbose_name='Класс / Возраст'),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Видны только в панели управления', verbose_name='Заметки администратора'),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('enrolled', 'Записан'), ('declined', 'Отказ')], default='new', max_length=15, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='URL из атрибута src= в коде вставки карты Google Maps', max_length=1000, verbose_name='Google Maps embed URL'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Рекомендуется 1200×500px', upload_to='gallery/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_accent_kg',
            field=models.CharField(default='ар бир бала үчүн', max_length=120, verbose_name='Заголовок строка 2 (кырг)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_accent_ru',
            field=models.CharField(default='для каждого ребёнка', max_length=120, verbose_name='Заголовок строка 2 (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tag_kg',
            field=models.CharField(max_length=40, verbose_name='Тег / классы (кырг)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
