# Generated by Django 6.0.3 on 2026-04-07 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0003_alter_aboutfeature_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_ru', models.SlugField(unique=True, verbose_name='Слаг (рус)')),
                ('slug_kg', models.SlugField(unique=True, verbose_name='Слаг (кырг)')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Название (рус)')),
                ('name_kg', models.CharField(max_length=50, verbose_name='Название (кырг)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория программы',
                'verbose_name_plural': 'Категории программ',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='class_size_ru',
            field=models.CharField(max_length=30, verbose_name='Кол-во учеников (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_ru',
            field=models.CharField(max_length=30, verbose_name='Длительность (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tag_ru',
            field=models.CharField(max_length=40, verbose_name='Тег / классы (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_site.programcategory', verbose_name='Категория программы'),
        ),
    ]
