# Generated by Django 6.0.3 on 2026-04-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0004_programcategory_alter_program_class_size_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcategory',
            name='slug_kg',
        ),
        migrations.RemoveField(
            model_name='programcategory',
            name='slug_ru',
        ),
        migrations.AddField(
            model_name='aboutfeature',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='contacts', help_text="Используется для генерации ЧПУ, например 'contacts'", max_length=60, verbose_name='Название (для слага)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='programcategory',
            name='slug',
            field=models.SlugField(default=2, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='program',
            name='class_size_ru',
            field=models.CharField(help_text='Например: 25 чел/класс', max_length=30, verbose_name='Кол-во учеников (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_ru',
            field=models.CharField(help_text='Например: 4 года', max_length=30, verbose_name='Длительность (рус)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tag_ru',
            field=models.CharField(help_text='Например: 1–4 классы', max_length=40, verbose_name='Тег / классы (рус)'),
        ),
    ]
